### ISSUE TITLE
Error initializing complex filters.

### ISSUE THREAD

**Issue by GN-c** [mifi/editly#111]
I'm trying to use editly with node js.
editly works perfectly on local machine, when ffmpeg is installed and available in PATH.
but when installing ffmpeg with [@ffmpeg-installer/ffmpeg](https://www.npmjs.com/package/@ffmpeg-installer/ffmpeg), ffprobe with [@ffprobe-installer/ffprobe](https://www.npmjs.com/package/@ffprobe-installer/ffprobe) and adding paths:
```
const ffmpegPath = require("@ffmpeg-installer/ffmpeg").path;
const ffprobePath = require("@ffprobe-installer/ffprobe").path;
const editSpec = {
  ffprobePath,
  ffmpegPath,
  outPath: "export/video.mp4",
```
editly executes with errors:
```
node index.js
WARNING: ffmpeg issue: Unknown version string
WARNING: ffprobe issue: Unknown version string
Extracting audio/silence from all clips
Mixing clip audio with arbitrary audio
Error: Command failed with exit code 1: D:\tameimpala\node_modules\@ffmpeg-installer\win32-x64\ffmpeg.exe -hide_banner -loglevel error -stream_loop 0 -i export\editly-tmp-yTV9y5sRArgTVze554fhk\audio-concat.flac -stream_loop 0 -i assets/audio.wav -filter_complex [0]atrim=start=0,adelay=delays=0:all=1[a0];[1]atrim=start=0,adelay=delays=1000:all=1,apad[a1];[a0][a1]amix=inputs=2:duration=first:dropout_transition=0:weights=1 1 -c:a flac -y export\editly-tmp-yTV9y5sRArgTVze554fhk\audio-mixed.flac
[Parsed_adelay_1 @ 000001ebf4d30c80] Option 'all' not found
[AVFilterGraph @ 000001ebf4cb8f40] Error initializing filter 'adelay' with args 'delays=0:all=1'
Error initializing complex filters.
Option not found
    at makeError (D:\tameimpala\node_modules\execa\lib\error.js:59:11)
    at handlePromise (D:\tameimpala\node_modules\execa\index.js:114:26)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async mixArbitraryAudio (D:\tameimpala\node_modules\editly\audio.js:196:5)
    at async editAudio (D:\tameimpala\node_modules\editly\audio.js:232:23)
    at async Editly (D:\tameimpala\node_modules\editly\index.js:73:34) {
  shortMessage: 'Command failed with exit code 1: D:\\tameimpala\\node_modules\\@ffmpeg-installer\\win32-x64\\ffmpeg.exe -hide_banner -loglevel error -stream_loop 0 -i export\\editly-tmp-yTV9y5sRArgTVze554fhk\\audio-concat.flac -stream_loop 0 -i assets/audio.wav -filter_complex [0]atrim=start=0,adelay=delays=0:all=1[a0];[1]atrim=start=0,adelay=delays=1000:all=1,apad[a1];[a0][a1]amix=inputs=2:duration=first:dropout_transition=0:weights=1 1 -c:a flac -y export\\editly-tmp-yTV9y5sRArgTVze554fhk\\audio-mixed.flac',
  command: 'D:\\tameimpala\\node_modules\\@ffmpeg-installer\\win32-x64\\ffmpeg.exe -hide_banner -loglevel error -stream_loop 0 -i export\\editly-tmp-yTV9y5sRArgTVze554fhk\\audio-concat.flac -stream_loop 0 -i assets/audio.wav -filter_complex [0]atrim=start=0,adelay=delays=0:all=1[a0];[1]atrim=start=0,adelay=delays=1000:all=1,apad[a1];[a0][a1]amix=inputs=2:duration=first:dropout_transition=0:weights=1 1 -c:a flac -y export\\editly-tmp-yTV9y5sRArgTVze554fhk\\audio-mixed.flac',
  exitCode: 1,
  signal: undefined,
  signalDescription: undefined,
  stdout: '',
  stderr: "[Parsed_adelay_1 @ 000001ebf4d30c80] Option 'all' not found\r\n" +
    "[AVFilterGraph @ 000001ebf4cb8f40] Error initializing filter 'adelay' with args 'delays=0:all=1'\r\n" +
    'Error initializing complex filters.\r\n' +
    'Option not found',
  failed: true,
  timedOut: false,
  isCanceled: false,
  killed: false
}
```
### index.js
```
const editly = require("editly");
const ffmpegPath = require("@ffmpeg-installer/ffmpeg").path;
const ffprobePath = require("@ffprobe-installer/ffprobe").path;

let images = ["1.jpg", "2.jpg", "3.jpg", "4.jpg", "5.jpg", "6.jpg"].map(
  (i) => "images/" + i
);

const editSpec = {
  ffprobePath,
  ffmpegPath,
  outPath: "export/video.mp4",
  width: 720,
  height: 720,
  fps: 30,
  audioTracks: [{ path: "assets/audio.wav", start: 1 }],
  defaults: {
    duration: 30 / images.length,
    transition: {
      name: "CrossZoom",
      duration: 0.8,
    },
  },
  clips: images.map((image, i) => {
    return {
      layers: [
        {
          type: "image",
          path: image,
          zoomDirection: i % 2 ? "out" : "in",
          zoomAmount: 0.3,
        },
      ],
    };
  }),
};

editly(editSpec)
  .then(() => {
    console.log(data);
  })
  .catch(console.error);
```
System with ffmpeg added in PATH (where works flawlessly)
```
Edition	Windows 10 Pro
Version	20H2
Installed on	‎11/‎11/‎2020
OS build	19042.685
Experience	Windows Feature Experience Pack 120.2212.551.0
```
### ffmpeg
![Screenshot 2021-02-02 171705](https://user-images.githubusercontent.com/64430939/106605676-9713ba00-657a-11eb-966e-0bff3a814a57.png)

> maybe it's issue of command line limitations?

- Same error does not come up when using fluent-ffmpeg with same configuration
- It still throws same error on firebase Cloud functions without @ffmpeg-installer and @ffprobe-installer | _ffmpeg is preinstalled_
- tested it on window 10, mac and firebase cloud functions (linux)

**Comment by mifi** [comment]
im suspecting old version of ffmpeg. please double check

**Comment by GN-c** [comment]
![image](https://user-images.githubusercontent.com/64430939/106879241-5475ed00-66f4-11eb-8877-69e83da7abd4.png)
It seems it's the latest version of ffmpeg^
in any case, what do you advice for running editly on node js servers?

**Comment by mifi** [comment]
2018 seems quite old to me
