### ISSUE TITLE
output.mp4: Permission denied

### ISSUE THREAD

**Issue by jrichardsz** [mifi/editly#120]
- [ ] I have tried with the newest version of editly: `npm i -g editly` or `npm i editly@latest`
- [ ] I have tried ffmpeg newest stable version
- [ ] I have searched for existing issues

### Environment

node -v
v10.21.0
npm -v
6.14.4
ffmpeg
version n4.3.1 Copyright (c) 2000-2020 the FFmpeg developers

### Scenario

I just want to create a video with:
```
editly   title:'My video'   c.png   title:'My slideshow'   c.png  title:'THE END'  --fast  --out output.mp4
```

But I got this error:

```
WARNING: ffmpeg issue: Unknown version string
WARNING: ffprobe issue: Command failed with ENOENT: ffprobe -version
spawn ffprobe ENOENT
250x250 15fps
  0% output.mp4: Permission denied
Caught error { Error: Command failed with EPIPE: ffmpeg -hide_banner -loglevel error -f rawvideo -vcodec rawvideo -pix_fmt rgba -s 250x250 -r 15 -i - -map 0:v:0 -vf format=yuv420p -vcodec libx264 -profile:v high -preset:v ultrafast -crf 18 -movflags faststart -y output.mp4
write EPIPE
    at afterWriteDispatched (internal/stream_base_commons.js:78:25)
    at writeGeneric (internal/stream_base_commons.js:73:3)
    at Socket._writeGeneric (net.js:714:5)
    at Socket._write (net.js:726:8)
    at doWrite (_stream_writable.js:415:12)
    at writeOrBuffer (_stream_writable.js:399:5)
    at Socket.Writable.write (_stream_writable.js:299:11)
    at Editly.Promise (/foo/.nvm/versions/node/v10.21.0/lib/node_modules/editly/index.js:367:66)
    at new Promise (<anonymous>)
    at Editly (/foo/.nvm/versions/node/v10.21.0/lib/node_modules/editly/index.js:367:30)
  errno: 'EPIPE',
  code: 'EPIPE',
  syscall: 'write',
  originalMessage: 'write EPIPE',
  shortMessage:
   'Command failed with EPIPE: ffmpeg -hide_banner -loglevel error -f rawvideo -vcodec rawvideo -pix_fmt rgba -s 250x250 -r 15 -i - -map 0:v:0 -vf format=yuv420p -vcodec libx264 -profile:v high -preset:v ultrafast -crf 18 -movflags faststart -y output.mp4\nwrite EPIPE',
  command:
   'ffmpeg -hide_banner -loglevel error -f rawvideo -vcodec rawvideo -pix_fmt rgba -s 250x250 -r 15 -i - -map 0:v:0 -vf format=yuv420p -vcodec libx264 -profile:v high -preset:v ultrafast -crf 18 -movflags faststart -y output.mp4',
  exitCode: undefined,
  signal: undefined,
  signalDescription: undefined,
  stdout: undefined,
  stderr: undefined,
  failed: true,
  timedOut: false,
  isCanceled: false,
  killed: false }
```

**Comment by jrichardsz** [comment]
For some reason, when I try in /tmp the error disappears but mp4 is not created :s 

```
editly   title:'My video'   c.png   title:'My slideshow'   c.png  title:'THE END'  --fast  --out output.mp4
WARNING: ffmpeg issue: Unknown version string
WARNING: ffprobe issue: Command failed with ENOENT: ffprobe -version
spawn ffprobe ENOENT
250x250 15fps
  0%   3%   7%  11%  14%  18%  22% Done with transition, switching to next transitionFromClip (1)
 22%  25%  29%  33%  37%  40% Done with transition, switching to next transitionFromClip (2)
 44%  48%  51%  55%  59% Done with transition, switching to next transitionFromClip (3)
 62%  66%  70%  74%  77% Done with transition, switching to next transitionFromClip (4)
 81%  85%  88%  92%  96% Done with transition, switching to next transitionFromClip (5)
No more transitionFromClip, done

Done. Output file can be found at:
output.mp4
```

I don't have any problems related to permission on my folders or apps. I never run Nodejs with sudo.

I will continue testing this tool!

**Comment by jrichardsz** [comment]
I tried with just ffmpeg and the error was the same. I re-installed the ffmpeg and everything works!
