### ISSUE TITLE
How do I use one long music track and multiple audio files for each clip?

### ISSUE THREAD

**Issue by Astraport** [mifi/editly#121]
I've tried this setup, but the music file starts again on every clip.
```
{
 width: 1280, height: 720, fps: 30,
  outPath: './commonFeatures.mp4',
  defaults: {
    transition: { name: 'random' },
  },
  clips: [
 { duration: 13, layers: [{type: 'detached-audio', path: './assets/winxp.mp3', mixVolume: 50, cutFrom: 0.5 }] },
{ duration: 13, layers: [{type: 'detached-audio', path: './assets/winxp.mp3', mixVolume: 50, cutFrom: 0.5 }] },
{ duration: 13, layers: [{type: 'detached-audio', path: './assets/winxp.mp3', mixVolume: 50, cutFrom: 0.5 }] },
  ],
  audioTracks: [
    { path: './assets/High [NCS Release] - JPB  (No Copyright Music)-R8ZRCXy5vhA.m4a', cutFrom: 18 },
  ],
}
```

**Comment by mifi** [comment]
Hi. I'm not sure I understand. I just tried this and the music file does not restart on every clip.

**Comment by Astraport** [comment]
>I just tried this and the music file does not restart on every clip.

My mistake, it seemed to me that there are repetitions.
But now another issue, if you set "loopAudio: true", then an error occurs ffmpeg:
```
C:\Users\Administrator>editly t.json5
WARNING: ffmpeg issue: Unknown version string
WARNING: ffprobe issue: Unknown version string
Extracting audio/silence from all clips
Mixing clip audio with arbitrary audio
Caught error Error: Command failed with exit code 1: ffmpeg -hide_banner -loglevel error -stream_loop 0 -i editly-tmp-8r-9Df0VVwsTVigyk8Hxk\audio-concat.flac -stream_loop -1 -i ./data/bg1.mp3 -stream_loop 0 -i ./data/narewasnd/0.mp3 -stream_loop 0 -i ./data/narewasnd/1.mp3 -stream_loop 0 -i ./data/narewasnd/2.mp3 -stream_loop 0 -i ./data/narewasnd/3.mp3 -stream_loop 0 -i ./data/narewasnd/4.mp3 -stream_loop 0 -i ./data/narewasnd/5.mp3 -stream_loop 0 -i ./data/narewasnd/6.mp3 -stream_loop 0 -i ./data/narewasnd/7.mp3 -stream_loop 0 -i ./data/narewasnd/8.mp3 -stream_loop 0 -i ./data/narewasnd/9.mp3 -stream_loop 0 -i ./data/narewasnd/10.mp3 -stream_loop 0 -i ./data/narewasnd/11.mp3 -filter_complex [0]atrim=start=0,adelay=delays=0:all=1[a0];[1]atrim=start=0,adelay=delays=0:all=1,apad[a1];[2]atrim=start=0:end=1,adelay=delays=0:all=1,apad[a2];[3]atrim=start=0:end=1,adelay=delays=5500:all=1,apad[a3];[4]atrim=start=0:end=1,adelay=delays=18000:all=1,apad[a4];[5]atrim=start=0:end=1,adelay=delays=46500:all=1,apad[a5];[6]atrim=start=0:end=1,adelay=delays=63000:all=1,apad[a6];[7]atrim=start=0:end=1,adelay=delays=83500:all=1,apad[a7];[8]atrim=start=0:end=1,adelay=delays=98000:all=1,apad[a8];[9]atrim=start=0:end=1,adelay=delays=116500:all=1,apad[a9];[10]atrim=start=0:end=1,adelay=delays=137000:all=1,apad[a10];[11]atrim=start=0:end=1,adelay=delays=153500:all=1,apad[a11];[12]atrim=start=0:end=1,adelay=delays=166000:all=1,apad[a12];[13]atrim=start=0:end=1,adelay=delays=179500:all=1,apad[a13];[a0][a1][a2][a3][a4][a5][a6][a7][a8][a9][a10][a11][a12][a13]amix=inputs=14:duration=first:dropout_transition=0:weights=1 1 50 50 50 50 50 50 50 50 50 50 50 50 -c:a flac -y editly-tmp-8r-9Df0VVwsTVigyk8Hxk\audio-mixed.flac
11430660 frame duplication too large, skipping
.....
```

**Comment by mifi** [comment]
can you provide the full error output?

**Comment by Astraport** [comment]
```
C:\Users\Administrator>editly t.json5
WARNING: ffmpeg issue: Unknown version string
WARNING: ffprobe issue: Unknown version string
Extracting audio/silence from all clips
Mixing clip audio with arbitrary audio
Caught error Error: Command failed with exit code 1: ffmpeg -hide_banner -loglevel error -stream_loop 0 -i editly-tmp-OdjjldwWRO8gawjbTILzD\audio-concat.flac -stream_loop -1 -i ./data/bg1.mp3 -stream_loop 0 -i ./data/narewasnd/0.mp3 -stream_loop 0 -i ./data/narewasnd/1.mp3 -stream_loop 0 -i ./data/narewasnd/2.mp3 -stream_loop 0 -i ./data/narewasnd/3.mp3 -stream_loop 0 -i ./data/narewasnd/4.mp3 -stream_loop 0 -i ./data/narewasnd/5.mp3 -stream_loop 0 -i ./data/narewasnd/6.mp3 -stream_loop 0 -i ./data/narewasnd/7.mp3 -stream_loop 0 -i ./data/narewasnd/8.mp3 -stream_loop 0 -i ./data/narewasnd/9.mp3 -stream_loop 0 -i ./data/narewasnd/10.mp3 -stream_loop 0 -i ./data/narewasnd/11.mp3 -filter_complex [0]atrim=start=0,adelay=delays=0:all=1[a0];[1]atrim=start=0,adelay=delays=0:all=1,apad[a1];[2]atrim=start=0,adelay=delays=0:all=1,apad[a2];[3]atrim=start=0,adelay=delays=5500:all=1,apad[a3];[4]atrim=start=0,adelay=delays=18000:all=1,apad[a4];[5]atrim=start=0,adelay=delays=46500:all=1,apad[a5];[6]atrim=start=0,adelay=delays=63000:all=1,apad[a6];[7]atrim=start=0,adelay=delays=83500:all=1,apad[a7];[8]atrim=start=0,adelay=delays=98000:all=1,apad[a8];[9]atrim=start=0,adelay=delays=116500:all=1,apad[a9];[10]atrim=start=0,adelay=delays=137000:all=1,apad[a10];[11]atrim=start=0,adelay=delays=153500:all=1,apad[a11];[12]atrim=start=0,adelay=delays=166000:all=1,apad[a12];[13]atrim=start=0,adelay=delays=179500:all=1,apad[a13];[a0][a1][a2][a3][a4][a5][a6][a7][a8][a9][a10][a11][a12][a13]amix=inputs=14:duration=first:dropout_transition=0:weights=1 1 50 50 50 50 50 50 50 50 50 50 50 50 -c:a flac -y editly-tmp-OdjjldwWRO8gawjbTILzD\audio-mixed.flac
11430660 frame duplication too large, skipping
22861321 frame duplication too large, skipping
34291983 frame duplication too large, skipping
45722643 frame duplication too large, skipping
57153307 frame duplication too large, skipping
68583967 frame duplication too large, skipping
80014631 frame duplication too large, skipping
91445287 frame duplication too large, skipping
102875951 frame duplication too large, skipping
114306615 frame duplication too large, skipping
125737271 frame duplication too large, skipping
137167935 frame duplication too large, skipping
148598591 frame duplication too large, skipping
160029263 frame duplication too large, skipping
171459919 frame duplication too large, skipping
182890575 frame duplication too large, skipping
194321247 frame duplication too large, skipping
205751903 frame duplication too large, skipping
217182559 frame duplication too large, skipping
228613231 frame duplication too large, skipping
240043887 frame duplication too large, skipping
251474543 frame duplication too large, skipping
262905215 frame duplication too large, skipping
274335871 frame duplication too large, skipping
285766527 frame duplication too large, skipping
297197183 frame duplication too large, skipping
308627839 frame duplication too large, skipping
320058527 frame duplication too large, skipping
331489183 frame duplication too large, skipping
342919839 frame duplication too large, skipping
354350495 frame duplication too large, skipping
365781151 frame duplication too large, skipping
377211807 frame duplication too large, skipping
388642495 frame duplication too large, skipping
400073151 frame duplication too large, skipping
411503807 frame duplication too large, skipping
422934463 frame duplication too large, skipping
434365119 frame duplication too large, skipping
445795775 frame duplication too large, skipping
457226463 frame duplication too large, skipping
468657119 frame duplication too large, skipping
480087775 frame duplication too large, skipping
491518431 frame duplication too large, skipping
502949087 frame duplication too large, skipping
514379743 frame duplication too large, skipping
525810431 frame duplication too large, skipping
537241087 frame duplication too large, skipping
Error while filtering: Invalid argument
Failed to inject frame into filter network: Invalid argument
Error while processing the decoded data for stream #1:0
    at makeError (C:\Users\Administrator\AppData\Roaming\npm\node_modules\editly\node_modules\execa\lib\error.js:59:11)
    at handlePromise (C:\Users\Administrator\AppData\Roaming\npm\node_modules\editly\node_modules\execa\index.js:114:26)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async mixArbitraryAudio (C:\Users\Administrator\AppData\Roaming\npm\node_modules\editly\audio.js:196:5)
    at async editAudio (C:\Users\Administrator\AppData\Roaming\npm\node_modules\editly\audio.js:232:23)
    at async Editly (C:\Users\Administrator\AppData\Roaming\npm\node_modules\editly\index.js:73:34)
    at async C:\Users\Administrator\AppData\Roaming\npm\node_modules\editly\cli.js:136:3 {
  shortMessage: 'Command failed with exit code 1: ffmpeg -hide_banner -loglevel error -stream_loop 0 -i editly-tmp-OdjjldwWRO8gawjbTILzD\\audio-concat.flac -stream_loop -1 -i ./data/bg1.mp3 -stream_loop 0 -i ./data/narewasnd/0.mp3 -stream_loop 0 -i ./data/narewasnd/1.mp3 -stream_loop 0 -i ./data/narewasnd/2.mp3 -stream_loop 0 -i ./data/narewasnd/3.mp3 -stream_loop 0 -i ./data/narewasnd/4.mp3 -stream_loop 0 -i ./data/narewasnd/5.mp3 -stream_loop 0 -i ./data/narewasnd/6.mp3 -stream_loop 0 -i ./data/narewasnd/7.mp3 -stream_loop 0 -i ./data/narewasnd/8.mp3 -stream_loop 0 -i ./data/narewasnd/9.mp3 -stream_loop 0 -i ./data/narewasnd/10.mp3 -stream_loop 0 -i ./data/narewasnd/11.mp3 -filter_complex [0]atrim=start=0,adelay=delays=0:all=1[a0];[1]atrim=start=0,adelay=delays=0:all=1,apad[a1];[2]atrim=start=0,adelay=delays=0:all=1,apad[a2];[3]atrim=start=0,adelay=delays=5500:all=1,apad[a3];[4]atrim=start=0,adelay=delays=18000:all=1,apad[a4];[5]atrim=start=0,adelay=delays=46500:all=1,apad[a5];[6]atrim=start=0,adelay=delays=63000:all=1,apad[a6];[7]atrim=start=0,adelay=delays=83500:all=1,apad[a7];[8]atrim=start=0,adelay=delays=98000:all=1,apad[a8];[9]atrim=start=0,adelay=delays=116500:all=1,apad[a9];[10]atrim=start=0,adelay=delays=137000:all=1,apad[a10];[11]atrim=start=0,adelay=delays=153500:all=1,apad[a11];[12]atrim=start=0,adelay=delays=166000:all=1,apad[a12];[13]atrim=start=0,adelay=delays=179500:all=1,apad[a13];[a0][a1][a2][a3][a4][a5][a6][a7][a8][a9][a10][a11][a12][a13]amix=inputs=14:duration=first:dropout_transition=0:weights=1 1 50 50 50 50 50 50 50 50 50 50 50 50 -c:a flac -y editly-tmp-OdjjldwWRO8gawjbTILzD\\audio-mixed.flac',
  command: 'ffmpeg -hide_banner -loglevel error -stream_loop 0 -i editly-tmp-OdjjldwWRO8gawjbTILzD\\audio-concat.flac -stream_loop -1 -i ./data/bg1.mp3 -stream_loop 0 -i ./data/narewasnd/0.mp3 -stream_loop 0 -i ./data/narewasnd/1.mp3 -stream_loop 0 -i ./data/narewasnd/2.mp3 -stream_loop 0 -i ./data/narewasnd/3.mp3 -stream_loop 0 -i ./data/narewasnd/4.mp3 -stream_loop 0 -i ./data/narewasnd/5.mp3 -stream_loop 0 -i ./data/narewasnd/6.mp3 -stream_loop 0 -i ./data/narewasnd/7.mp3 -stream_loop 0 -i ./data/narewasnd/8.mp3 -stream_loop 0 -i ./data/narewasnd/9.mp3 -stream_loop 0 -i ./data/narewasnd/10.mp3 -stream_loop 0 -i ./data/narewasnd/11.mp3 -filter_complex [0]atrim=start=0,adelay=delays=0:all=1[a0];[1]atrim=start=0,adelay=delays=0:all=1,apad[a1];[2]atrim=start=0,adelay=delays=0:all=1,apad[a2];[3]atrim=start=0,adelay=delays=5500:all=1,apad[a3];[4]atrim=start=0,adelay=delays=18000:all=1,apad[a4];[5]atrim=start=0,adelay=delays=46500:all=1,apad[a5];[6]atrim=start=0,adelay=delays=63000:all=1,apad[a6];[7]atrim=start=0,adelay=delays=83500:all=1,apad[a7];[8]atrim=start=0,adelay=delays=98000:all=1,apad[a8];[9]atrim=start=0,adelay=delays=116500:all=1,apad[a9];[10]atrim=start=0,adelay=delays=137000:all=1,apad[a10];[11]atrim=start=0,adelay=delays=153500:all=1,apad[a11];[12]atrim=start=0,adelay=delays=166000:all=1,apad[a12];[13]atrim=start=0,adelay=delays=179500:all=1,apad[a13];[a0][a1][a2][a3][a4][a5][a6][a7][a8][a9][a10][a11][a12][a13]amix=inputs=14:duration=first:dropout_transition=0:weights=1 1 50 50 50 50 50 50 50 50 50 50 50 50 -c:a flac -y editly-tmp-OdjjldwWRO8gawjbTILzD\\audio-mixed.flac',
  exitCode: 1,
  signal: undefined,
  signalDescription: undefined,
  stdout: '',
  stderr: '11430660 frame duplication too large, skipping\r\n' +
    '22861321 frame duplication too large, skipping\r\n' +
    '34291983 frame duplication too large, skipping\r\n' +
    '45722643 frame duplication too large, skipping\r\n' +
    '57153307 frame duplication too large, skipping\r\n' +
    '68583967 frame duplication too large, skipping\r\n' +
    '80014631 frame duplication too large, skipping\r\n' +
    '91445287 frame duplication too large, skipping\r\n' +
    '102875951 frame duplication too large, skipping\r\n' +
    '114306615 frame duplication too large, skipping\r\n' +
    '125737271 frame duplication too large, skipping\r\n' +
    '137167935 frame duplication too large, skipping\r\n' +
    '148598591 frame duplication too large, skipping\r\n' +
    '160029263 frame duplication too large, skipping\r\n' +
    '171459919 frame duplication too large, skipping\r\n' +
    '182890575 frame duplication too large, skipping\r\n' +
    '194321247 frame duplication too large, skipping\r\n' +
    '205751903 frame duplication too large, skipping\r\n' +
    '217182559 frame duplication too large, skipping\r\n' +
    '228613231 frame duplication too large, skipping\r\n' +
    '240043887 frame duplication too large, skipping\r\n' +
    '251474543 frame duplication too large, skipping\r\n' +
    '262905215 frame duplication too large, skipping\r\n' +
    '274335871 frame duplication too large, skipping\r\n' +
    '285766527 frame duplication too large, skipping\r\n' +
    '297197183 frame duplication too large, skipping\r\n' +
    '308627839 frame duplication too large, skipping\r\n' +
    '320058527 frame duplication too large, skipping\r\n' +
    '331489183 frame duplication too large, skipping\r\n' +
    '342919839 frame duplication too large, skipping\r\n' +
    '354350495 frame duplication too large, skipping\r\n' +
    '365781151 frame duplication too large, skipping\r\n' +
    '377211807 frame duplication too large, skipping\r\n' +
    '388642495 frame duplication too large, skipping\r\n' +
    '400073151 frame duplication too large, skipping\r\n' +
    '411503807 frame duplication too large, skipping\r\n' +
    '422934463 frame duplication too large, skipping\r\n' +
    '434365119 frame duplication too large, skipping\r\n' +
    '445795775 frame duplication too large, skipping\r\n' +
    '457226463 frame duplication too large, skipping\r\n' +
    '468657119 frame duplication too large, skipping\r\n' +
    '480087775 frame duplication too large, skipping\r\n' +
    '491518431 frame duplication too large, skipping\r\n' +
    '502949087 frame duplication too large, skipping\r\n' +
    '514379743 frame duplication too large, skipping\r\n' +
    '525810431 frame duplication too large, skipping\r\n' +
    '537241087 frame duplication too large, skipping\r\n' +
    'Error while filtering: Invalid argument\r\n' +
    'Failed to inject frame into filter network: Invalid argument\r\n' +
    'Error while processing the decoded data for stream #1:0',
  failed: true,
  timedOut: false,
  isCanceled: false,
  killed: false
}
```

**Comment by mifi** [comment]
which version of ffmpeg?

**Comment by Astraport** [comment]
> which version of ffmpeg?

```
ffmpeg version n4.3.1-221-gd08bcbffff Copyright (c) 2000-2021 the FFmpeg developers
built with gcc 9.3-win32 (GCC) 20200320
configuration: --prefix=/ffbuild/prefix --pkg-config-flags=--static --pkg-config=pkg-config --cross-prefix=x86_64-w64-mingw32- --arch=x86_64 --target-os=mingw32 --enable-gpl --enable-version3 --disable-debug --disable-w32threads --enable-pthreads --enable-iconv --enable-zlib --enable-libxml2 --enable-libfreetype --enable-libfribidi --enable-gmp --enable-lzma --enable-fontconfig --enable-opencl --enable-libvmaf --disable-vulkan --enable-libvorbis --enable-amf --enable-libaom --enable-avisynth --enable-libdav1d --enable-libdavs2 --enable-ffnvcodec --enable-cuda-llvm --disable-libglslang --enable-libass --enable-libbluray --enable-libmp3lame --enable-libopus --enable-libtheora --enable-libvpx --enable-libwebp --enable-libmfx --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-librav1e --enable-librubberband --enable-schannel --enable-sdl2 --enable-libsoxr --enable-libsrt --enable-libtwolame --enable-libvidstab --enable-libx264 --enable-libx265 --enable-libxavs2 --enable-libxvid --enable-libzimg --extra-cflags=-DLIBTWOLAME_STATIC --extra-cxxflags= --extra-ldflags=-pthread --extra-libs=-lgomp
libavutil      56. 51.100 / 56. 51.100
libavcodec     58. 91.100 / 58. 91.100
libavformat    58. 45.100 / 58. 45.100
libavdevice    58. 10.100 / 58. 10.100
libavfilter     7. 85.100 /  7. 85.100
libswscale      5.  7.100 /  5.  7.100
libswresample   3.  7.100 /  3.  7.100
libpostproc    55.  7.100 / 55.  7.100
```
