### ISSUE TITLE
RangeError [ERR_INVALID_OPT_VALUE]: The value "22464900000" is invalid for option "size"

### ISSUE THREAD

**Issue by BrunoQuaresma** [mifi/editly#150]
Hi folks,

When I try to run Editly, I'm facing the following error: 
```bash
➜  video-edit node index.js
ffmpeg version 4.4
ffprobe version 4.4
547x547 30fps
RangeError [ERR_INVALID_OPT_VALUE]: The value "107546873400" is invalid for option "size"
    at Function.allocUnsafe (buffer.js:386:3)
    at module.exports (/Users/brunoquaresma/workspace/video-edit/node_modules/editly/sources/videoFrameSource.js:65:22)
    at pMap.concurrency (/Users/brunoquaresma/workspace/video-edit/node_modules/editly/sources/frameSource.js:46:31)
    at /Users/brunoquaresma/workspace/video-edit/node_modules/p-map/index.js:57:28 {
  code: 'ERR_INVALID_OPT_VALUE'
}
➜  video-edit sudo node index.js
Password:
➜  video-edit sudo node index.js
➜  video-edit sudo node index.js
ffmpeg version 4.4
ffprobe version 4.4
250x250 15fps
RangeError [ERR_INVALID_OPT_VALUE]: The value "22464900000" is invalid for option "size"
    at Function.allocUnsafe (buffer.js:386:3)
    at module.exports (/Users/brunoquaresma/workspace/video-edit/node_modules/editly/sources/videoFrameSource.js:65:22)
    at pMap.concurrency (/Users/brunoquaresma/workspace/video-edit/node_modules/editly/sources/frameSource.js:46:31)
    at /Users/brunoquaresma/workspace/video-edit/node_modules/p-map/index.js:57:28 {
  code: 'ERR_INVALID_OPT_VALUE'
}
➜  video-edit sudo node index.js
➜  video-edit sudo node index.js
ffmpeg version 4.4
ffprobe version 4.4
{
  outPath: './output/output.mp4',
  width: 547,
  height: 547,
  fps: 25,
  keepSourceAudio: true,
  verbose: true,
  defaults: {
    duration: 2,
    layerType: {
      'image-overlay': {
        path: './image.png',
        position: {
          x: 0,
          y: 0,
        },
        width: 1,
        height: 1,
      },
    },
  },
  clips: [
    {
      layers: [
        {
          type: 'video',
          path: './video.mp4',
          width: 225,
          height: 404,
          left: 0.29,
          top: 0.17,
        },
      ],
    },
  ],
  fast: true,
}
Calculated {
  clips: [
    {
      transition: {
        duration: 0,
      },
      duration: 4.046,
      layers: [
        {
          type: 'video',
          path: './video.mp4',
          width: 225,
          height: 404,
          left: 0.29,
          top: 0.17,
          cutFrom: 0,
          cutTo: 4.046,
          inputDuration: 4.046,
          framerateStr: '30/1',
          inputWidth: 320,
          inputHeight: 568,
          start: 0,
          layerDuration: 4.046,
          speedFactor: 1,
        },
      ],
    },
  ],
  arbitraryAudio: [],
}
{ tmpDir: 'output/editly-tmp-SZlLbnzAdrTLKj-npZDVb' }
Extracting audio/silence from all clips
Mixing clip audio with arbitrary audio
250x250 15fps
ffmpeg -hide_banner -loglevel error -f rawvideo -vcodec rawvideo -pix_fmt rgba -s 250x250 -r 15 -i - -i /Users/brunoquaresma/workspace/video-edit/output/editly-tmp-SZlLbnzAdrTLKj-npZDVb/clip0-layer0-audio.flac -map 0:v:0 -map 1:a:0 -acodec aac -b:a 128k -vf format=yuv420p -vcodec libx264 -profile:v high -preset:v ultrafast -crf 18 -movflags faststart -y ./output/output.mp4
createFrameSource video clip 0 layer 0
scale=56250:99844
Cleanup
Output ffmpeg exited null
RangeError [ERR_INVALID_OPT_VALUE]: The value "22464900000" is invalid for option "size"
    at Function.allocUnsafe (buffer.js:386:3)
    at module.exports (/Users/brunoquaresma/workspace/video-edit/node_modules/editly/sources/videoFrameSource.js:65:22)
    at pMap.concurrency (/Users/brunoquaresma/workspace/video-edit/node_modules/editly/sources/frameSource.js:46:31)
    at /Users/brunoquaresma/workspace/video-edit/node_modules/p-map/index.js:57:28
    at processTicksAndRejections (internal/process/task_queues.js:95:5) {
  code: 'ERR_INVALID_OPT_VALUE'
}
```

Here is the code:
```js
const editly = require("editly");

const editSpec = {
  outPath: "./output/output.mp4",
  width: 547,
  height: 547,
  fps: 25,
  keepSourceAudio: true,
  verbose: true,
  defaults: {
    duration: 2,
    layerType: {
      "image-overlay": {
        path: "./image.png",
        position: { x: 0, y: 0 },
        width: 1,
        height: 1,
      },
    },
  },
  clips: [
    {
      layers: [
        {
          type: "video",
          path: "./video.mp4",
          width: 225,
          height: 404,
          left: 0.29,
          top: 0.17,
        },
      ],
    },
  ],
  fast: true,
};

editly(editSpec)
  .then(() => console.log("Success"))
  .catch(console.error);
```

Thanks in advance!

**Comment by BrunoQuaresma** [comment]
I found the issue. That happened because I passed width as an absolute value in the video layer instead of using it from 0 to 1.
