### ISSUE TITLE
Error: gl returned null on Docker image

### ISSUE THREAD

**Issue by BrunoQuaresma** [mifi/editly#154]
Hi folks,

I'm trying to deploy an API that uses editly as a dependency using Docker. I have the following Dockerfile:
```
FROM  node:14

# Create app directory
WORKDIR /usr/src/app

# Install app dependencies
# A wildcard is used to ensure both package.json AND package-lock.json are copied
# where available (npm@5+)
COPY package*.json ./
COPY tsconfig.json ./

# Necessary to run editly and node-gyp
RUN apt-get update && apt-get install -y \
    ffmpeg \
    build-essential \
    libxi-dev \
    libglu1-mesa-dev \
    libglew-dev \
    pkg-config

RUN npm install
# If you are building your code for production
# RUN npm ci --only=production

# Bundle app source
COPY . .

EXPOSE 8080
CMD [ "npm", "start" ]
```

The build and initialization work fine, but when editly starts to render the video an error is raised.

```
Error: gl returned null, this probably means that some dependencies are not installed. See README.
    at module.exports (/usr/src/app/node_modules/editly/glTransitions.js:12:11)
    at Editly (/usr/src/app/node_modules/editly/index.js:172:60)
```

**Comment by jeremym148** [comment]
@mifi  hi so for that issue what is the final solution ?
I checkd on the closed issue but I dont find the solution..

**Comment by mifi** [comment]
I'm not a docker expert so I don't know. You can ask inside the open issue #33 - maybe someone has found a solution
