### ISSUE TITLE
"[Parsed_adelay_1 @ 0x559b17bc3340] Option 'all' not found\n" + "[AVFilterGraph @ 0x559b17bec200] Error initializing filter 'adelay' with args 'dela ys=0:all=1'\n" +     'Error initializing complex filters.\n' +     'Option not found',

### ISSUE THREAD

**Issue by Apopheosis** [mifi/editly#155]
I want to rewrite audio to an existing video using editly, it works perfectly on windows, but on linux it throws an error:

ffmpeg version 4.1.6
ffprobe version 4.1.6
Extracting audio/silence from all clips
Mixing clip audio with arbitrary audio
Error: Command failed with exit code 1: ffmpeg -hide_banner -loglevel error -stream_loop
 0 -i /home/bitnami/belbot/images/editly-tmp-Zhn-1ZYBu4zwFyAxL8M5e/clip0-audio.flac -str
eam_loop 0 -i ./audio/puk.mp3 -filter_complex [0]atrim=start=0,adelay=delays=0:all=1[a0]
;[1]atrim=start=0,adelay=delays=0:all=1,apad[a1];[a0][a1]amix=inputs=2:duration=first:dr
opout_transition=0:weights=1 1,dynaudnorm=g=3:maxgain=100 -c:a flac -y images/editly-tmp
-Zhn-1ZYBu4zwFyAxL8M5e/audio-mixed.flac
[Parsed_adelay_1 @ 0x559b17bc3340] Option 'all' not found
[AVFilterGraph @ 0x559b17bec200] Error initializing filter 'adelay' with args 'delays=0:
all=1'
Error initializing complex filters.
Option not found
    at makeError (/home/bitnami/belbot/node_modules/execa/lib/error.js:59:11)
    at handlePromise (/home/bitnami/belbot/node_modules/execa/index.js:114:26)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async mixArbitraryAudio (/home/bitnami/belbot/node_modules/editly/audio.js:196:5)
    at async editAudio (/home/bitnami/belbot/node_modules/editly/audio.js:232:23)
    at async Editly (/home/bitnami/belbot/node_modules/editly/index.js:73:34)
    at async Client.<anonymous> (/home/bitnami/belbot/index.js:128:17) {
  shortMessage: 'Command failed with exit code 1: ffmpeg -hide_banner -loglevel error -s
tream_loop 0 -i /home/bitnami/belbot/images/editly-tmp-Zhn-1ZYBu4zwFyAxL8M5e/clip0-audio
.flac -stream_loop 0 -i ./audio/puk.mp3 -filter_complex [0]atrim=start=0,adelay=delays=0
:all=1[a0];[1]atrim=start=0,adelay=delays=0:all=1,apad[a1];[a0][a1]amix=inputs=2:duratio
n=first:dropout_transition=0:weights=1 1,dynaudnorm=g=3:maxgain=100 -c:a flac -y images/
editly-tmp-Zhn-1ZYBu4zwFyAxL8M5e/audio-mixed.flac',
  command: 'ffmpeg -hide_banner -loglevel error -stream_loop 0 -i /home/bitnami/belbot/i
mages/editly-tmp-Zhn-1ZYBu4zwFyAxL8M5e/clip0-audio.flac -stream_loop 0 -i ./audio/puk.mp
3 -filter_complex [0]atrim=start=0,adelay=delays=0:all=1[a0];[1]atrim=start=0,adelay=del
ays=0:all=1,apad[a1];[a0][a1]amix=inputs=2:duration=first:dropout_transition=0:weights=1
 1,dynaudnorm=g=3:maxgain=100 -c:a flac -y images/editly-tmp-Zhn-1ZYBu4zwFyAxL8M5e/audio
-mixed.flac',
  exitCode: 1,
  signal: undefined,
  signalDescription: undefined,
  stdout: '',
  stderr: "[Parsed_adelay_1 @ 0x559b17bc3340] Option 'all' not found\n" +
    "[AVFilterGraph @ 0x559b17bec200] Error initializing filter 'adelay' with args 'dela
ys=0:all=1'\n" +
    'Error initializing complex filters.\n' +
    'Option not found',
  failed: true,
  timedOut: false,
  isCanceled: false,
  killed: false
}

- [ ] I have tried with the newest version of editly: `npm i -g editly` or `npm i editly@latest`
- [ ] I have tried ffmpeg newest stable version
- [ ] I have searched for existing issues

**Comment by mifi** [comment]
you are not using newest ffmpeg version

**Comment by mifi** [comment]
The log you pasted says

ffmpeg version 4.1.6
ffprobe version 4.1.6

But the newest version of ffmpeg is 4.4

**Comment by Apopheosis** [comment]
After some researching and installing the latest ffmpeg version, now I came up across this error:

Unrecognized option 'preset:v'.
Error splitting the argument list: Option not found
  0% Error: Command failed with exit code 1: ffmpeg -hide_banner -loglevel error -f rawv
ideo -vcodec rawvideo -pix_fmt rgba -s 576x1024 -r 24000/1001 -i - -i images/editly-tmp-
58MWxEK9UDap5hx6630RV/audio-mixed.flac -map 0:v:0 -map 1:a:0 -acodec aac -b:a 128k -vf f
ormat=yuv420p -vcodec libx264 -profile:v high -preset:v medium -crf 18 -movflags faststa
rt -y ./images/video.mp4
    at makeError (/home/bitnami/belbot/node_modules/execa/lib/error.js:59:11)
    at handlePromise (/home/bitnami/belbot/node_modules/execa/index.js:114:26)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  shortMessage: 'Command failed with exit code 1: ffmpeg -hide_banner -loglevel error -f
 rawvideo -vcodec rawvideo -pix_fmt rgba -s 576x1024 -r 24000/1001 -i - -i images/editly
-tmp-58MWxEK9UDap5hx6630RV/audio-mixed.flac -map 0:v:0 -map 1:a:0 -acodec aac -b:a 128k 
-vf format=yuv420p -vcodec libx264 -profile:v high -preset:v medium -crf 18 -movflags fa
ststart -y ./images/video.mp4',
  command: 'ffmpeg -hide_banner -loglevel error -f rawvideo -vcodec rawvideo -pix_fmt rg
ba -s 576x1024 -r 24000/1001 -i - -i images/editly-tmp-58MWxEK9UDap5hx6630RV/audio-mixed
.flac -map 0:v:0 -map 1:a:0 -acodec aac -b:a 128k -vf format=yuv420p -vcodec libx264 -pr
ofile:v high -preset:v medium -crf 18 -movflags faststart -y ./images/video.mp4',
  exitCode: 1,
  signal: undefined,
  signalDescription: undefined,
  stdout: undefined,
  stderr: undefined,
  failed: true,
  timedOut: false,
  isCanceled: false,
  killed: false
}

ffmpeg version N-104327-g1902a60dda 

![image](https://user-images.githubusercontent.com/8437116/137034043-728e88bb-d371-4428-bcd4-dedf0e129b3c.png)

**Comment by mifi** [comment]
I think your ffmpeg build is missing x264. Try to download a static build from here: https://ffmpeg.org/download.html

**Comment by Neerajbridging** [comment]
Hello @mifi,

Hope you're doing good. 

I am using Editly https://github.com/mifi/editly on ubuntu.

Please find the attachment of the issue and specification. 

I have done with all the functionality and deployed my code on the ubuntu server. It is not working when I am adding Audio files.

I will appreciate your help!!!!

![image](https://user-images.githubusercontent.com/97034875/147936511-3cab62e0-4e36-48fb-b5a2-9260a33dd3e7.png)


![issue](https://user-images.githubusercontent.com/97034875/147936256-b311da80-e343-4236-a8bc-6eb04d01b870.png)
