### ISSUE TITLE
exit code on ffmpeg fail

### ISSUE THREAD

**Issue by chapmanjacobd** [mifi/editly#19]
when ffmpeg exits with nonzero exit code then editly should also exit nonzero.

currently:
```
{ Error: Command failed with exit code 1: ffprobe -select_streams v:0 -show_entries stream -of json 
ffprobe version 4.1.5 Copyright (c) 2007-2020 the FFmpeg developers
  built with gcc 9 (GCC)
  configuration: blah blah blah

undefined: No such file or directory
{

}
    at makeError (/home/xk/amp/node_modules/execa/lib/error.js:58:11)
    at handlePromise (/home/xk/amp/node_modules/execa/index.js:114:26)
    at processTicksAndRejections (internal/process/task_queues.js:86:5)
  shortMessage:
   'Command failed with exit code 1: ffprobe -select_streams v:0 -show_entries stream -of json ',
  command: 'ffprobe -select_streams v:0 -show_entries stream -of json ',
  exitCode: 1,
  signal: undefined,
  signalDescription: undefined,
  stdout: '{\n\n}',
```
but node exits 0

to reproduce this you can incorrectly say file instead of path:

```
editly({
  fast: true,
  outPath: "./customFabric.mp4",
  clips: [
    {
      layers: [{ type: "video", file: "~/amp/test.webm" }],
    }]
})
```

**Comment by chapmanjacobd** [comment]
the behavior is a little strange. when I use path then node will correctly use a nonzero exit code:

```
~/amp/dancer1.webm: No such file or directory
{

}
    at makeError (/home/xk/amp/node_modules/execa/lib/error.js:58:11)
    at handlePromise (/home/xk/amp/node_modules/execa/index.js:114:26)
    at processTicksAndRejections (internal/process/task_queues.js:86:5)
  shortMessage:
   'Command failed with exit code 1: ffprobe -select_streams v:0 -show_entries stream -of json ~/amp/dancer1.webm',
  command:
   'ffprobe -select_streams v:0 -show_entries stream -of json ~/amp/dancer1.webm',


[ffmpeg/demuxer] mov,mp4,m4a,3gp,3g2,mj2: moov atom not found
[lavf] avformat_open_input() failed
[ffmpeg/demuxer] mov,mp4,m4a,3gp,3g2,mj2: moov atom not found
[lavf] avformat_open_input() failed
Failed to recognize file format.


Exiting... (Errors when loading file)
```

**Comment by mifi** [comment]
Thanks. I have now added an exit code 1 when error occurs

**Comment by gunar** [comment]
Somewhat related, it seems errors in the `layers` array throw an AssertionError but won't make the process exit with a non-zero error. Can we change that? Useful when doing `node script.js && vlc output.mp4`, which is what I do during development.

**Comment by gunar** [comment]
Never mind, I can do this myself already. I had `.catch(console.error)` instead of `.catch(process.exit)`. My bad!
