### ISSUE TITLE
Issues installing editly on RHEL7 system

### ISSUE THREAD

**Issue by upnorth173** [mifi/editly#199]
- [ X] I have tried with the newest version of editly: `npm i -g editly` or `npm i editly@latest`
- [X ] I have tried ffmpeg newest stable version
- [X ] I have searched for existing issues
- I am trying to install editly on a RHEL7 system (I can on a RHEL8 system, but I have to get this running on RHEL7 system).  It all appears to be created correctly by running: npm i -g editly --unsafe, but when I run editly (from /usr/local/bin) it comes back with:
editly --version
internal/modules/cjs/loader.js:1144
  return process.dlopen(module, path.toNamespacedPath(filename));
                 ^

Error: /lib64/libstdc++.so.6: version `CXXABI_1.3.9' not found (required by /usr/local/lib/node_modules/editly/node_modules/canvas/build/Release/canvas.node)
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:1144:18)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:12)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at require (internal/modules/cjs/helpers.js:101:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/editly/node_modules/canvas/lib/bindings.js:3:18)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:12) {
  code: 'ERR_DLOPEN_FAILED'
}

I have updated gcc etc by installing RHEL devtoolset-8.  How can I get editly to install and run on RHEL7?

Thanks

**Comment by MDxWARRIORxOP** [comment]
im getting the same error, Im on windows 10

**Comment by MDxWARRIORxOP** [comment]
```bash
node:internal/modules/cjs/loader:1302
  return process.dlopen(module, path.toNamespacedPath(filename));
                 ^

Error: The specified module could not be found.
\\?\D:\Learning-Nodejs\YoutubeShortsGenerator\node_modules\gl\build\Release\webgl.node
    at Module._extensions..node (node:internal/modules/cjs/loader:1302:18)       
    at Module.load (node:internal/modules/cjs/loader:1081:32)
    at Module._load (node:internal/modules/cjs/loader:922:12)
    at Module.require (node:internal/modules/cjs/loader:1105:19)
    at require (node:internal/modules/cjs/helpers:103:18)
    at bindings (D:\Learning-Nodejs\YoutubeShortsGenerator\node_modules\bindings\bindings.js:112:48)
    at Object.<anonymous> (D:\Learning-Nodejs\YoutubeShortsGenerator\node_modules\gl\src\javascript\native-gl.js:1:40)
    at Module._compile (node:internal/modules/cjs/loader:1218:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1272:10)
    at Module.load (node:internal/modules/cjs/loader:1081:32) {
  code: 'ERR_DLOPEN_FAILED'
}

```
