### ISSUE TITLE
Remote requests are not allowed with AWS s3 presigned URLs

### ISSUE THREAD

**Issue by matukaking** [mifi/editly#231]
Caught error AssertionError [ERR_ASSERTION]: Remote requests are not allowed
    at assertFileValid (file:///C:/Users/albre/AppData/Roaming/npm/node_modules/editly/util.js:165:5)
    at handleLayer (file:///C:/Users/albre/AppData/Roaming/npm/node_modules/editly/parseConfig.js:55:13)
    at pMap.concurrency (file:///C:/Users/albre/AppData/Roaming/npm/node_modules/editly/parseConfig.js:164:14)
    at file:///C:/Users/albre/AppData/Roaming/npm/node_modules/editly/node_modules/p-map/index.js:141:26 {
  generatedMessage: false,
  code: 'ERR_ASSERTION',
  actual: undefined,
  expected: true,
  operator: '=='
}

**Comment by mifi** [comment]
use allowRemoteRequests

**Comment by matukaking** [comment]
Could you tell me where can i do that please?
