### ISSUE TITLE
Problems installing on ubuntu bionic

### ISSUE THREAD

**Issue by altrujade** [mifi/editly#28]
Installed on ubuntu bionic with buildin nodejs.
first there seem to be some libraries missing in the dependecies or install instructions: libxi-dev, libxext-dev, libx11-dev

When finally everything installed I get this error:
 editly --help
/usr/local/lib/node_modules/editly/node_modules/fs-extra/lib/mkdirs/make-dir.js:86
      } catch {
              ^

SyntaxError: Unexpected token {
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:616:28)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/editly/node_modules/fs-extra/lib/mkdirs/index.js:3:44)

**Comment by mifi** [comment]
Thanks for reporting. I will add to linux specific instructions. I think your other issue may be due to a too old node.js version? It is recommended to run newest stable (12)

**Comment by altrujade** [comment]
Thank you for the fast reply. I updated to node 14 and reinstalled editly.
Now my problem is this (sorry I'm not a nodejs person):
$ editly
internal/modules/cjs/loader.js:1235
  return process.dlopen(module, path.toNamespacedPath(filename));
                 ^

Error: The module '/usr/local/lib/node_modules/editly/node_modules/canvas/build/Release/canvas.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 57. This version of Node.js requires
NODE_MODULE_VERSION 83. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or `npm install`).
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:1235:18)
    at Module.load (internal/modules/cjs/loader.js:1034:32)
    at Function.Module._load (internal/modules/cjs/loader.js:923:14)
    at Module.require (internal/modules/cjs/loader.js:1074:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/editly/node_modules/canvas/lib/bindings.js:3:18)
    at Module._compile (internal/modules/cjs/loader.js:1185:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1205:10)
    at Module.load (internal/modules/cjs/loader.js:1034:32)
    at Function.Module._load (internal/modules/cjs/loader.js:923:14)

**Comment by altrujade** [comment]
I got it running by removing /usr/lib/node_modules/editly and then installing it without the -g flag.

**Comment by mifi** [comment]
Yeah when you reinstall node you also need to reinstall any modules that has binary built dependencies (as editly does)
