### ISSUE TITLE
Add ffmpeg version check

### ISSUE THREAD

**Issue by majidmanzarpour** [mifi/editly#34]
I've tried converting my audio file to different formats (mp3 lame, ogg) and I keep getting complaints about AAC:

```$ xvfb-run -s "-ac -screen 0 1280x1024x24" editly editly.json
720x1280 30fps
createFrameSource linear-gradient clip 0 layer 0
createFrameSource title clip 0 layer 1
createFrameSource fill-color clip 1 layer 0
createFrameSource title clip 1 layer 1
  0% [aac @ 0x1dec620] The encoder 'aac' is experimental but experimental codecs are not enabled, add '-strict -2' if you want to use it.
Output ffmpeg caught error Error: write EPIPE
    at afterWriteDispatched (internal/stream_base_commons.js:146:25)
    at writeGeneric (internal/stream_base_commons.js:137:3)
    at Socket._writeGeneric (net.js:698:11)
    at Socket._write (net.js:710:8)
    at doWrite (_stream_writable.js:417:12)
    at writeOrBuffer (_stream_writable.js:401:5)
    at Socket.Writable.write (_stream_writable.js:301:11)
    at /usr/local/lib/node_modules/editly/index.js:406:51
    at new Promise (<anonymous>)
    at module.exports (/usr/local/lib/node_modules/editly/index.js:406:15) {
  errno: 'EPIPE',
  code: 'EPIPE',
  syscall: 'write'
}
Loop failed Error: write EPIPE
    at afterWriteDispatched (internal/stream_base_commons.js:146:25)
    at writeGeneric (internal/stream_base_commons.js:137:3)
    at Socket._writeGeneric (net.js:698:11)
    at Socket._write (net.js:710:8)
    at doWrite (_stream_writable.js:417:12)
    at writeOrBuffer (_stream_writable.js:401:5)
    at Socket.Writable.write (_stream_writable.js:301:11)
    at /usr/local/lib/node_modules/editly/index.js:406:51
    at new Promise (<anonymous>)
    at module.exports (/usr/local/lib/node_modules/editly/index.js:406:15) {
  errno: 'EPIPE',
  code: 'EPIPE',
  syscall: 'write'```

**Comment by chapmanjacobd** [comment]
@mifi  maybe we should automatically print ffmpeg version when we handle an error

**Comment by majidmanzarpour** [comment]
@chapmanjacobd ```ffmpeg version 2.8.15-0ubuntu0.16.04.1 Copyright (c) 2000-2018 the FFmpeg developers
built with gcc 5.4.0 (Ubuntu 5.4.0-6ubuntu1~16.04.10) 20160609```

**Comment by chapmanjacobd** [comment]
I don't think that you'll see this error if you update ffmpeg to a more recent version but it would be good if we could handle older versions of ffmpeg correctly @mifi

**Comment by majidmanzarpour** [comment]
Thanks @chapmanjacobd that worked. 

For anyone else running into this issue, I upgrade to ffmpeg 4 on an older version of Ubuntu using these instructions http://ubuntuhandbook.org/index.php/2018/10/install-ffmpeg-4-0-2-ubuntu-18-0416-04/

**Comment by mifi** [comment]
Ok, thanks. I agree we should add a version check or maybe just include ffmpeg #23, and we can add to Requirements

**Comment by mifi** [comment]
This is now implemented and will be released in the newest version
