### ISSUE TITLE
Installation fails on AWS EBS 

### ISSUE THREAD

**Issue by srameshr** [mifi/editly#70]
When I include ```editly``` in my package.json, the installation will fail with the following error.

```
2020/09/19 14:47:08.774860 [ERROR] An error occurred during execution of command [app-deploy] - [Use NPM to install dependencies]. Stop running the command. Error: Command /bin/sh -c npm --production install failed with error exit status 1. Stderr:npm WARN deprecated opn@6.0.0: The package has been renamed to `open`
npm WARN deprecated request-promise-native@1.0.9: request-promise-native has been deprecated because it extends the now deprecated request package, see https://github.com/request/request/issues/3142
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
prebuild-install WARN install libXext.so.6: cannot open shared object file: No such file or directory
Package x11 was not found in the pkg-config search path.
Perhaps you should add the directory containing `x11.pc'
to the PKG_CONFIG_PATH environment variable
No package 'x11' found
Package xi was not found in the pkg-config search path.
Perhaps you should add the directory containing `xi.pc'
to the PKG_CONFIG_PATH environment variable
No package 'xi' found
Package xext was not found in the pkg-config search path.
Perhaps you should add the directory containing `xext.pc'
to the PKG_CONFIG_PATH environment variable
No package 'xext' found
gyp: Call to 'pkg-config --libs-only-l x11 xi xext' returned exit status 1 while in angle/src/angle.gyp. while loading dependencies of binding.gyp while trying to load binding.gyp
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/opt/elasticbeanstalk/node-install/node-v12.18.3-linux-x64/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:351:16)
gyp ERR! stack     at ChildProcess.emit (events.js:315:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12)
gyp ERR! System Linux 4.14.192-147.314.amzn2.x86_64
gyp ERR! command "/opt/elasticbeanstalk/node-install/node-v12.18.3-linux-x64/bin/node" "/opt/elasticbeanstalk/node-install/node-v12.18.3-linux-x64/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /var/app/staging/node_modules/gl
gyp ERR! node -v v12.18.3
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok 
npm WARN mnews@1.0.0 No description
npm WARN mnews@1.0.0 No repository field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! gl@4.6.1 install: `prebuild-install || node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the gl@4.6.1 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2020-09-19T14_47_08_754Z-debug.log
```

Any documentation to fix this on ```.ebextensions```?

**Comment by srameshr** [comment]
Figured it out.

**Comment by doverradio** [comment]
> Figured it out.

I am facing this same issue.  How did you solve it?

**Comment by matheuscampbell** [comment]
> Descobri isso.



> > Descobri isso.
> 
> Estou enfrentando o mesmo problema. Como você resolveu isso?

Me too.
How solve it???

**Comment by aloisdg** [comment]
Same issue on arch

**Comment by AlbanMinassian** [comment]
Resolved with (ubuntu 22)

- `sudo apt install ffprobe`
- `sudo apt-get install -y build-essential libxi-dev libglu1-mesa-dev libglew-dev pkg-config`
- `sudo apt-get install libcairo2-dev libpango1.0-dev libjpeg-dev libgif-dev librsvg2-dev`
- `npm i -g editly`
