### ISSUE TITLE
Image to video  - Could not get frame filename number 2 from pattern error

### ISSUE THREAD

**Issue by maksym-plotnikov** [mifi/editly#73]
During generating video from image I'm having such issue:
```
ffmpeg -f rawvideo -vcodec rawvideo -pix_fmt rgba -s 1080x1920 -r 30 -i - -map 0:v:0 -vf format=yuv420p -vcodec libx264 -profile:v high -preset:v medium -crf 18 -movflags faststart -y /public/tmp/68388e5f-80f3-4a5b-85be-73c709089230_2f20349b-a87f-4f40-b55d-a992af32031c/partial-0.png
ffmpeg version N-50742-ga7245adee3-static https://johnvansickle.com/ffmpeg/  Copyright (c) 2000-2019 the FFmpeg developers
  built with gcc 6.3.0 (Debian 6.3.0-18+deb9u1) 20170516
  configuration: --enable-gpl --enable-version3 --enable-static --disable-debug --disable-ffplay --disable-indev=sndio --disable-outdev=sndio --cc=gcc-6 --enable-fontconfig --enable-frei0r --enable-gnutls --enable-gmp --enable-libgme --enable-gray --enable-libaom --enable-libfribidi --enable-libass --enable-libvmaf --enable-libfreetype --enable-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-librubberband --enable-libsoxr --enable-libspeex --enable-libsrt --enable-libvorbis --enable-libopus --enable-libtheora --enable-libvidstab --enable-libvo-amrwbenc --enable-libvpx --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxml2 --enable-libdav1d --enable-libxvid --enable-libzvbi --enable-libzimg
  libavutil      56. 35.101 / 56. 35.101
  libavcodec     58. 62.100 / 58. 62.100
  libavformat    58. 35.100 / 58. 35.100
  libavdevice    58.  9.100 / 58.  9.100
  libavfilter     7. 66.100 /  7. 66.100
  libswscale      5.  6.100 /  5.  6.100
  libswresample   3.  6.100 /  3.  6.100
  libpostproc    55.  6.100 / 55.  6.100
createFrameSource image clip 0 layer 0
Loading /public/tmp/68388e5f-80f3-4a5b-85be-73c709089230_2f20349b-a87f-4f40-b55d-a992af32031c/partial-0.png
Writing frame: 0 from clip 0 (frame 0)
Input #0, rawvideo, from 'pipe:':
  Duration: N/A, start: 0.000000, bitrate: 1990656 kb/s
    Stream #0:0: Video: rawvideo (RGBA / 0x41424752), rgba, 1080x1920, 1990656 kb/s, 30 tbr, 30 tbn, 30 tbc
Stream mapping:
  Stream #0:0 -> #0:0 (rawvideo (native) -> h264 (libx264))
[libx264 @ 0x6a32cc0] using cpu capabilities: MMX2 SSE2Fast SSSE3 SSE4.2 AVX FMA3 BMI2 AVX2
[libx264 @ 0x6a32cc0] profile High, level 4.0, 4:2:0, 8-bit
Output #0, image2, to '/public/tmp/68388e5f-80f3-4a5b-85be-73c709089230_2f20349b-a87f-4f40-b55d-a992af32031c/00-partial-0.png':
  Metadata:
    encoder         : Lavf58.35.100
    Stream #0:0: Video: h264 (libx264), yuv420p, 1080x1920, q=-1--1, 30 fps, 30 tbn, 30 tbc
    Metadata:
      encoder         : Lavc58.62.100 libx264
    Side data:
      cpb: bitrate max/min/avg: 0/0/0 buffer size: 0 vbv_delay: N/A
Writing frame: 1 from clip 0 (frame 1)
Writing frame: 2 from clip 0 (frame 2)
Writing frame: 3 from clip 0 (frame 3)
Writing frame: 4 from clip 0 (frame 4)
Writing frame: 5 from clip 0 (frame 5)e=00:00:00.00 bitrate=N/A speed=   0x    
Writing frame: 6 from clip 0 (frame 6)
Writing frame: 7 from clip 0 (frame 7)
Writing frame: 8 from clip 0 (frame 8)e=00:00:00.00 bitrate=N/A speed=   0x    
Writing frame: 9 from clip 0 (frame 9)
Writing frame: 10 from clip 0 (frame 10)
Writing frame: 11 from clip 0 (frame 11)00:00:00.00 bitrate=N/A speed=   0x    
Writing frame: 12 from clip 0 (frame 12)
Writing frame: 13 from clip 0 (frame 13)
Writing frame: 14 from clip 0 (frame 14)00:00:00.00 bitrate=N/A speed=   0x    
Writing frame: 15 from clip 0 (frame 15)
Writing frame: 16 from clip 0 (frame 16)
Writing frame: 17 from clip 0 (frame 17)00:00:00.00 bitrate=N/A speed=   0x    
Writing frame: 18 from clip 0 (frame 18)
Writing frame: 19 from clip 0 (frame 19)
Writing frame: 20 from clip 0 (frame 20)00:00:00.00 bitrate=N/A speed=   0x    
Writing frame: 21 from clip 0 (frame 21)
Writing frame: 22 from clip 0 (frame 22)
Writing frame: 23 from clip 0 (frame 23)00:00:00.00 bitrate=N/A speed=   0x    
Writing frame: 24 from clip 0 (frame 24)
Writing frame: 25 from clip 0 (frame 25)
Writing frame: 26 from clip 0 (frame 26)00:00:00.00 bitrate=N/A speed=   0x    
Writing frame: 27 from clip 0 (frame 27)
Writing frame: 28 from clip 0 (frame 28)
Writing frame: 29 from clip 0 (frame 29)00:00:00.00 bitrate=N/A speed=   0x    
Writing frame: 30 from clip 0 (frame 30)
Writing frame: 31 from clip 0 (frame 31)
Writing frame: 32 from clip 0 (frame 32)00:00:00.00 bitrate=N/A speed=   0x    
Writing frame: 33 from clip 0 (frame 33)
Writing frame: 34 from clip 0 (frame 34)
Writing frame: 35 from clip 0 (frame 35)00:00:00.00 bitrate=N/A speed=   0x    
Writing frame: 36 from clip 0 (frame 36)
Writing frame: 37 from clip 0 (frame 37)
Writing frame: 38 from clip 0 (frame 38)00:00:00.00 bitrate=N/A speed=   0x    
Writing frame: 39 from clip 0 (frame 39)
Writing frame: 40 from clip 0 (frame 40)
Writing frame: 41 from clip 0 (frame 41)00:00:00.00 bitrate=N/A speed=   0x    
Writing frame: 42 from clip 0 (frame 42)
Writing frame: 43 from clip 0 (frame 43)
Writing frame: 44 from clip 0 (frame 44)00:00:00.00 bitrate=N/A speed=   0x    
Writing frame: 45 from clip 0 (frame 45)
Writing frame: 46 from clip 0 (frame 46)
Writing frame: 47 from clip 0 (frame 47)00:00:00.00 bitrate=N/A speed=   0x    
Writing frame: 48 from clip 0 (frame 48)
Writing frame: 49 from clip 0 (frame 49)
Writing frame: 50 from clip 0 (frame 50)00:00:00.00 bitrate=N/A speed=   0x    
Writing frame: 51 from clip 0 (frame 51)
[**image2 @ 0x6a2ef00] Could not get frame filename number 2 from pattern '/public/tmp/68388e5f-80f3-4a5b-85be-73c709089230_2f20349b-a87f-4f40-b55d-a992af32031c/partial-0.png'. Use '-frames:v 1' for a single image, or '-update' option, or use a pattern such as %03d within the filename.
av_interleaved_write_frame(): Invalid argument**
Writing frame: 52 from clip 0 (frame 52)
frame=   52 fps=4.9 q=24.0 Lsize=N/A time=00:00:00.00 bitrate=N/A speed=   0x    
video:31kB audio:0kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: unknown
[libx264 @ 0x6a32cc0] frame I:1     Avg QP: 8.56  size: 19854
[libx264 @ 0x6a32cc0] frame P:13    Avg QP:17.48  size:  8965
[libx264 @ 0x6a32cc0] frame B:38    Avg QP:25.91  size:  2677
[libx264 @ 0x6a32cc0] consecutive B-frames:  1.9%  0.0%  5.8% 92.3%
[libx264 @ 0x6a32cc0] mb I  I16..4: 69.5% 21.3%  9.2%
[libx264 @ 0x6a32cc0] mb P  I16..4:  3.1%  0.3%  1.2%  P16..4:  5.1%  3.3%  1.4%  0.0%  0.0%    skip:85.7%
[libx264 @ 0x6a32cc0] mb B  I16..4:  1.1%  0.1%  0.1%  B16..8:  4.3%  1.7%  0.4%  direct: 1.0%  skip:91.4%  L0:46.5% L1:32.9% BI:20.6%
[libx264 @ 0x6a32cc0] 8x8 transform intra:14.0% inter:21.5%
[libx264 @ 0x6a32cc0] coded y,uvDC,uvAC intra: 6.2% 0.0% 0.0% inter: 1.7% 0.0% 0.0%
[libx264 @ 0x6a32cc0] i16 v,h,dc,p: 88% 11%  1%  0%
[libx264 @ 0x6a32cc0] i8 v,h,dc,ddl,ddr,vr,hd,vl,hu: 58%  3% 39%  0%  0%  0%  0%  0%  0%
[libx264 @ 0x6a32cc0] i4 v,h,dc,ddl,ddr,vr,hd,vl,hu: 57% 17% 22%  1%  1%  1%  0%  1%  0%
[libx264 @ 0x6a32cc0] i8c dc,h,v,p: 100%  0%  0%  0%
[libx264 @ 0x6a32cc0] Weighted P-Frames: Y:0.0% UV:0.0%
[libx264 @ 0x6a32cc0] ref P L0: 64.0%  2.1% 17.6% 16.2%
[libx264 @ 0x6a32cc0] ref B L0: 61.6% 28.9%  9.5%
[libx264 @ 0x6a32cc0] ref B L1: 80.5% 19.5%
[libx264 @ 0x6a32cc0] kb/s:1099.02
Conversion failed!
Output ffmpeg caught error Error: write EPIPE
    at WriteWrap.onWriteComplete [as oncomplete] (internal/stream_base_commons.js:92:16)
    at WriteWrap.callbackTrampoline (internal/async_hooks.js:120:14) {
  errno: 'EPIPE',
  code: 'EPIPE',
  syscall: 'write'
}
Loop failed Error: write EPIPE
    at WriteWrap.onWriteComplete [as oncomplete] (internal/stream_base_commons.js:92:16)
    at WriteWrap.callbackTrampoline (internal/async_hooks.js:120:14) {
  errno: 'EPIPE',
  code: 'EPIPE',
  syscall: 'write'
}
(node:9253) UnhandledPromiseRejectionWarning: Error: write EPIPE
    at WriteWrap.onWriteComplete [as oncomplete] (internal/stream_base_commons.js:92:16)
    at WriteWrap.callbackTrampoline (internal/async_hooks.js:120:14)
(node:9253) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 4)

```
Error message and https://trac.ffmpeg.org/wiki/Errors says that we need to change frame pattern or add `update, 1` flag to continuously overwrite image with new images.

I updated outputArgs array inside index.js with  '-update', 1,' flag and this solves issue.
@mifi I can probably create a PR for that if needed.

**Comment by maksym-plotnikov** [comment]
@mifi or You can just add this to index.js:362 
```
...
 '-crf', '18',
 '-update', 1,  <---- HERE
  '-movflags', 'faststart',
...
```

**Comment by mifi** [comment]
I'm not sure what you're trying to do here. What is you command line and your edit spec json?

**Comment by maksym-plotnikov** [comment]
Funny thing that I can't reproduce it right now.. It maybe some issue inside my code. So I will close that issue for now. If I could catch it on the future - i will update STR. Sorry for troubles!
